const db = require('../config/db')

// db('profiles')
//     .then(profiles => profiles.map(profile => profile.name))
//     .then(name => console.log(name))
//     .catch(err => console.log(err.sqlMessage))
//     .finally(() => db.destroy())

// db('profiles')
//     .map(profile => profile.name)
//     .then(name => console.log(name))
//     .catch(err => console.log(err.sqlMessage))
//     .finally(() => db.destroy())

// db.select().from('profiles')
//     .limit(2)
//     .offset(3)
//     .then(profiles => console.log(profiles))
//     .catch(err => console.log(err.sqlMessage))
//     .finally(() => db.destroy())

db('profiles')
    // .where({id:2})
    // .where("id", "=", 2)
    // .where('name', 'like', '%m%')
    // .whereNot({id:2})
    .whereIn('id', [1,2,3])
    .then(profiles => console.log(profiles))
    .catch(err => console.log(err.sqlMessage))
    .finally(() => db.destroy())